### ISSUE TITLE
Trying to install chromix on ubuntu 12.04 node.js produces a stack-trace.

### ISSUE THREAD

**Issue by tinkster** [smblott-github/chromix#13]
'''
info it worked if it ends with ok
verbose cli [ 'node', '/usr/bin/npm', 'install', '-g', 'chromix' ]
info using npm@1.1.4
info using node@v0.6.12
verbose config file /root/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
silly exec /usr/bin/node "/usr/share/npm/bin/npm-get-uid-gid.js" "nobody" 1000
silly spawning [ '/usr/bin/node',
silly spawning   [ '/usr/share/npm/bin/npm-get-uid-gid.js', 'nobody', 1000 ],
silly spawning   null ]
silly output from getuid/gid {"uid":65534,"gid":1000}
silly output from getuid/gid 
verbose cache add [ 'chromix', null ]
silly cache add: name, spec, args [ undefined, 'chromix', [ 'chromix', null ] ]
verbose parsed url { pathname: 'chromix', path: 'chromix', href: 'chromix' }
verbose addNamed [ 'chromix', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'chromix', '', false ]
verbose raw, before any munging chromix
verbose url resolving [ 'https://registry.npmjs.org/', './chromix' ]
verbose url resolved https://registry.npmjs.org/chromix
http GET https://registry.npmjs.org/chromix
ERR! Error: failed to fetch from registry: chromix
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1261:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! You may report this log at:
ERR!     <http://bugs.debian.org/npm>
ERR! or use
ERR!     reportbug --attach /root/npm-debug.log npm
ERR! 
ERR! System Linux 3.13.0-35-generic
ERR! command "node" "/usr/bin/npm" "install" "-g" "chromix"
ERR! cwd /root
ERR! node -v v0.6.12
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: chromix
verbose exit [ 1, true ]
'''

**Comment by tinkster** [comment]
Apparently that's a global debian/ubuntu issue.

https://bugs.launchpad.net/ubuntu/+source/npm/+bug/1271929/comments/4

'''
npm config set ca=""
'''
sorted me out
